//Testar as requisições - Schema Usuário
//Bye, Bye Postman :) (Mas claro, ainda dá para utilizá-lo se preferir)
//Instale a extensão REST Client no Visual Studio Code para conseguir utilizar este recurso

###
// GET Usuário atual
@baseUrl = http://localhost:4000
GET {{baseUrl}}/usuario/eu
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNWZhMzQyOWY4ZDUwYmMyNTU5YTFhYTQzIn0sImlhdCI6MTYwNDUzNTQ5OCwiZXhwIjoxNjA0NTM5MDk4fQ.1yvIBmuQGG5XZgdaRBBvO1OsFIGHuR0Yhzb2e2p8ZVc
###
// POST Login Usuário
POST {{baseUrl}}/usuario/login
Content-Type: application/json

{
    "email": "ricardo.leme@gmail.com",
    "senha": "secreta"}

###
// POST Novo Usuário
POST {{baseUrl}}/usuario/novo
Content-Type: application/json

{
    "nome": "Ricardo Leme",
    "email": "ricardo.leme@gmail.com",
    "senha": "secreta",
    "tipo": "administrador"}